spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/friend_ss
      username: root
      password: 1234

#配置mybatis
mybatis:
  type-aliases-package: com.example.friendss.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml




